=== MohawkMEDIC/SharedHealthIntegrationComponents/org.marc.shic.cda/src/main/resources/CodeTranslation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 (http://www.altova.com) by Laura Graham (Mohawk College) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Code">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element name="Translations">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Code" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="code"/>
			<xs:attribute name="codeSystem"/>
			<xs:attribute name="codeSystemName"/>
			<xs:attribute name="codeSystemVersion"/>
			<xs:attribute name="displayName"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="CodeList">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Code" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== MohawkMEDIC/SharedHealthIntegrationComponents/org.marc.shic.cda/src/main/resources/SampleTranslation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 (http://www.altova.com) by Laura Graham (Mohawk College) -->
<!--Sample XML file generated by XMLSpy v2011 (http://www.altova.com)-->
<CodeList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CodeTranslation.xsd">
	<Code codeSystem="1.2.3.4.5" displayName="some Drug Material Code DisplayName" codeSystemVersion="version 1" codeSystemName="Some CodeSystemName" code="12345">
		<Translations>
			<Code codeSystem="1.2.3.4.5.6" displayName="some Drug Translated Material Code DisplayName 6" codeSystemVersion="version 1" codeSystemName="Some Translated CodeSystemName 6" code="123456"/>
			<Code codeSystem="1.2.3.4.5.6.7" displayName="some Drug Translated Material Code DisplayName 7" codeSystemVersion="version 1" codeSystemName="Some Translated CodeSystemName 7" code="1234567"/>
            <Code codeSystem="2.16.840.1.113883.6.88" displayName="Dummy Translated RxNorm Drug" codeSystemVersion="version 1" codeSystemName="RxNorm" code="1111111"/>
		</Translations>
	</Code>
	<Code codeSystem="1.2.3.4.5" displayName="some Drug Material Code DisplayName" codeSystemVersion="version 1" codeSystemName="Some CodeSystemName" code="Some Drug Material Code 2">
		<Translations>
			<Code codeSystem="1.2.3.4.5.6" displayName="some Drug Translated Material Code DisplayName 6.2" codeSystemVersion="version 1" codeSystemName="Some Translated CodeSystemName 6" code="Some Transalted Drug Material Code 6.2"/>
			<Code codeSystem="1.2.3.4.5.6.7" displayName="some Drug Translated Material Code DisplayName 6.2" codeSystemVersion="version 1" codeSystemName="Some Translated CodeSystemName 7" code="Some Transalted Drug Material Code 6.2"/>
		</Translations>
	</Code>
</CodeList>
